use std::path::Path;
use csv::Writer;
use chrono::SecondsFormat;
use tracing::info;

use crate::models::{RequestRecord, TestSummary};

pub fn write_csv(
    records: &[RequestRecord],
    output_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = Path::new(output_path);

    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let mut writer = Writer::from_path(path)?;

    // Header CSV
    writer.write_record([
        "request_id",
        "worker_id",
        "started_at",
        "finished_at",
        "response_time_ms",
        "status_code",
        "success",
        "response_size_bytes",
        "error_message",
    ])?;

    // Data rows
    for r in records {
        writer.write_record([
            r.request_id.to_string(),
            r.worker_id.to_string(),
            r.started_at.to_rfc3339_opts(SecondsFormat::Millis, true),
            r.finished_at.to_rfc3339_opts(SecondsFormat::Millis, true),
            format!("{:.4}", r.response_time_ms),
            r.status_code.to_string(),
            r.success.to_string(),
            r.response_size_bytes.to_string(),
            r.error_message.clone().unwrap_or_default(),
        ])?;
    }

    writer.flush()?;

    info!("✅ CSV detail are saved: {}", output_path);
    Ok(())
}

pub fn write_summary(
    summary: &TestSummary,
    config_json: &str,
    output_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = Path::new(output_path);

    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let content = format_summary_text(summary, config_json);
    std::fs::write(path, &content)?;

    info!("✅ Summary are saved: {}", output_path);
    Ok(())
}

fn format_summary_text(s: &TestSummary, config_json: &str) -> String {
    let separator = "═".repeat(60);
    let thin_sep  = "─".repeat(60);

    let started  = s.test_started_at.to_rfc3339_opts(SecondsFormat::Millis, true);
    let finished = s.test_finished_at.to_rfc3339_opts(SecondsFormat::Millis, true);

    format!(
r#"
{sep}
  API PERFORMANCE TEST — SUMMARY REPORT
{sep}

  Test Name    : {test_name}
  URL          : {url}
  HTTP Method  : {method}
  Started At   : {started}
  Finished At  : {finished}

{thin}
  CONFIGURATION
{thin}
  Parallel Workers    : {workers}
  Total Req (planned) : {planned}
  Timeout (ms)        : (see configuration bellow)

{thin}
  HASIL KESELURUHAN
{thin}
  Total Duration      : {duration:.3} second
  Total Req Sent      : {total_sent}
  Success (2xx)       : {success}
  Failed              : {failed}
  Success Rate        : {success_rate:.2}%

{thin}
  THROUGHPUT (TPS)
{thin}
  TPS Overall         : {tps_all:.2} requests/second
  TPS Success Only    : {tps_ok:.2} requests/second

  Interpretasi:
    - TPS Overall = all request (sucess + failed) / total duration
    - TPS Success = only sucess request  / total duration

{thin}
  RESPONSE TIME STATISTICS (miliseconds)
{thin}
  Minimum             : {rt_min:.4} ms
  Maximum             : {rt_max:.4} ms
  Average (Mean)      : {rt_avg:.4} ms
  Std Deviation       : {rt_std:.4} ms
  Median    (P50)     : {rt_p50:.4} ms
  P75                 : {rt_p75:.4} ms
  P90                 : {rt_p90:.4} ms
  P95                 : {rt_p95:.4} ms
  P99                 : {rt_p99:.4} ms

{thin}
  DISTRIBUTION STATUS CODE
{thin}
  {status_dist}

{thin}
  CONFIGURATION TEST (JSON)
{thin}
{config_json}

{sep}
  Generated by api_perf_test v1.0.0
{sep}
"#,
        sep        = separator,
        thin       = thin_sep,
        test_name  = s.test_name,
        url        = s.url,
        method     = s.method,
        started    = started,
        finished   = finished,
        workers    = s.parallel_workers,
        planned    = s.total_requests_planned,
        duration   = s.total_duration_secs,
        total_sent = s.total_requests_sent,
        success    = s.successful_requests,
        failed     = s.failed_requests,
        success_rate = s.success_rate_percent,
        tps_all    = s.tps_overall,
        tps_ok     = s.tps_success,
        rt_min     = s.response_time_min_ms,
        rt_max     = s.response_time_max_ms,
        rt_avg     = s.response_time_avg_ms,
        rt_std     = s.response_time_stddev_ms,
        rt_p50     = s.response_time_p50_ms,
        rt_p75     = s.response_time_p75_ms,
        rt_p90     = s.response_time_p90_ms,
        rt_p95     = s.response_time_p95_ms,
        rt_p99     = s.response_time_p99_ms,
        status_dist = s.status_code_distribution,
        config_json = config_json,
    )
}

pub fn write_summary_json(
    summary: &TestSummary,
    output_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = Path::new(output_path);

    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let json = serde_json::to_string_pretty(summary)?;
    std::fs::write(path, json)?;

    info!("✅ Summary JSON saved: {}", output_path);
    Ok(())
}
